language: php
php: 5.5
install:
    - composer self-update
    - pear install pear/PHP_CodeSniffer
    - phpenv rehash
script:
    - composer update --prefer-dist
    - phpunit
    - phpcs -s Checker.php



